[package]
name = "rs_loader_impl"
version = "0.1.0"
edition = "2021"

[lib]
name = "rs_loader_impl"
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"

[workspace]
members = ["bridge_abi", "metacall_registrator"]

[dependencies]
bridge_abi = { path = "./bridge_abi" }
metacall_registrator = { path = "./metacall_registrator" }
