[package]
name = "rs_loader_impl"
version = "0.1.0"
edition = "2021"

[lib]
name = "rs_loader_impl"
crate-type = ["cdylib"]

[package.metadata.rust-analyzer]
rustc_private = true

[profile.release]
opt-level = "z"

[workspace]
members = ["parser", "metacall_registrator"]

[dependencies]
metacall_registrator = { path = "metacall_registrator" }
