[package]
authors = ["Mahdi Sharifi <devraymondsh@gmail.com>", "Vicente Eduardo Ferrer Garcia <vic798@gmail.com>", "Swarnim Arun <swarnimarun11@gmail.com>"]
description = "Call NodeJS, TypeScript, Python, C#, Ruby... functions from Rust (a Rust Port for MetaCall)."
edition = "2021"
keywords = ["programming-language", "ffi", "polyglot", "metacall", "function-mesh", "inter-language", "polyglot-programming"]
license = "Apache-2.0"
name = "metacall"
readme = "README.md"
repository = "https://github.com/metacall/core/tree/develop/source/ports/rs_port"
version = "0.4.0"

[lib]
name = "metacall"
crate-type = ["lib"]
path = "src/lib.rs"
edition = "2021"

[dependencies]
metacall-inline = { path = "./inline", version = "0.2.0" }

[build-dependencies]
bindgen = { version = "0.64.0", default-features = false, features = ["runtime", "logging", "which-rustfmt"]}
