name: Linux Test

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master

jobs:
  linux-test:
    name: Linux (Ubuntu) GCC Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildtype: [debug, release]

    env:
      DEBIAN_FRONTEND:             noninteractive
      LTTNG_UST_REGISTER_TIMEOUT:  0
      NUGET_XMLDOC_MODE:           skip
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install, build and run tests
        run: ./docker-compose.sh test
        env:
          METACALL_BUILD_TYPE: ${{ matrix.buildtype }}
