name: Linux Test

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux-test:
    name: Linux GCC Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [debug, release]
        build_image: ["debian:bookworm-slim", "debian:bullseye-slim", "ubuntu:jammy"] # TODO: "alpine:3.17"

    env:
      DEBIAN_FRONTEND:             noninteractive
      LTTNG_UST_REGISTER_TIMEOUT:  0
      NUGET_XMLDOC_MODE:           skip
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install, build and run tests
        run: ./docker-compose.sh test
        env:
          METACALL_BUILD_TYPE: ${{ matrix.build_type }}
          METACALL_BASE_IMAGE: ${{ matrix.build_image }}
