name: MacOS Test

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
      - develop

jobs:
  mac-test:
    name: MacOS Clang Test
    runs-on: macos-latest

    strategy:
      matrix:
        buildtype: [debug, release]
    
    env:
      LTTNG_UST_REGISTER_TIMEOUT:  0
      NUGET_XMLDOC_MODE:           skip
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

        # TODO: This must go in metacall-environment-macos.sh as base dependencies
      - name: Configure Clang 
        run: |
          brew install clang cmake git wget gnupg ca-certificates

      - name: Set up the environment
        run: sh ./tools/metacall-environment-macos.sh $METACALL_INSTALL_OPTIONS
        env:
          METACALL_INSTALL_OPTIONS: python nodejs # ruby netcore5 typescript file rpc wasm java c cobol rust rapidjson funchook swig pack # clangformat v8rep51 coverage

      - name: Configure
        run: |
          METACALL_PATH=$PWD
          mkdir -p "$METACALL_PATH/build"
          cd "$METACALL_PATH/build"
          sh ../tools/metacall-configure.sh $METACALL_BUILD_OPTIONS
        env:
          METACALL_BUILD_OPTIONS: ${{ matrix.buildtype }} scripts ports tests sanitizer # nodejs python java sanitizer ruby netcore5 typescript file rpc wasm java c cobol rust examples dynamic install pack benchmarks # v8 coverage

      - name: Build
        working-directory: ./build
        run: |
          make -j$(getconf _NPROCESSORS_ONLN)
          ctest -j$(getconf _NPROCESSORS_ONLN) --timeout 5400 --output-on-failure --test-output-size-failed 3221000000 -C $BUILD_TYPE
        env:
          METACALL_BUILD_OPTIONS: ${{ matrix.buildtype }} tests
          BUILD_TYPE: Debug # TODO: This must go in the build script for macos and it should be detected from buildtype passed in METACALL_BUILD_OPTIONS
