# Note: This is duplicated from sanitizer.yml in order to keep the ci running if one of both sanitizers fail
name: Thread Sanitizer Test

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux-sanitizer-gcc:
    name: Linux (Ubuntu) GCC Thread Sanitizer Test
    runs-on: ubuntu-latest
    env:
      SANITIZER_SKIP_SUMMARY: 1

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install, build and run thread sanitizer tests
        run: ./docker-compose.sh test-thread-sanitizer

  linux-sanitizer-clang:
    name: Linux (Ubuntu) Clang Sanitizer Test
    runs-on: ubuntu-latest
    env:
      SANITIZER_SKIP_SUMMARY: 1

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends wget
          wget -O - https://apt.llvm.org/llvm.sh | sudo bash -s -- 16
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 40
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-16 80
          sudo update-alternatives --config cc
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 40
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-16 80
          sudo update-alternatives --config c++
          /usr/bin/cc --version
          /usr/bin/c++ --version

      - name: Install, build and run thread sanitizer tests
        env:
          CC: /usr/bin/clang-16
          CXX: /usr/bin/clang++-16
        run: ./docker-compose.sh test-thread-sanitizer
